Mvvm
andreilemdyanov/StudyApp pull request #4
Opened 2020-12-26 22:26 UTC by andreilemdyanov

2021-01-08 05:03 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
не совсем понятно зачем тебе нужна эта логика здесь. расскажи, что ты делаешь?
и нельзя сохранять контекст активити (this) в переменные - это очень плохая практика, которая ведет к мемори ликам.

2021-01-08 05:03 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/movie_details/ActorsAdapter.kt
> +    private var inflater = LayoutInflater.from(APP_ACTIVITY)
нельзя так делать. используй контекст из parent.context (LayoutInflater.from(parent.context).inflate(...))

2021-01-09 10:49 UTC, andreilemdyanov commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
Хотел добавить абстракцию в виде интерфейса для легкого тестирования и подмены имплементации с локального JSON на Retrofit  и данные из сети. Контекст активити нельзя сохранять в переменную даже в сингл активити приложении при условии, что в onDestroy() присваивать null переменной?

2021-01-10 21:59 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
контекст вообще никуда лучше не сохранять - это очень плохая практика. если есть такая необходимость - значит архитектура построена не совсем удачно и надо ее срочно пересмотреть

2021-01-10 22:00 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
в скоупе активити у тебя контекст доступен через this / baseContext / applicationContext

2021-01-10 22:02 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
в скоупе фрагмента - через context
во вспомогательные классы вроде utils контекст должен передаваться через сингатуру метода

2021-01-10 22:24 UTC, kmormysh commented on app/src/main/java/ru/fundamentals/studyapp/screens/MainActivity.kt
> +        ).get(MoviesViewModel::class.java)
так же у тебя получилась не совсем корректная абстракция. ты здесь говоришь, что активити зависит от MoviesViewModel

2021-01-10 22:30 UTC, kmormysh requested changes
1. убрать сохранение контекста в глобальную переменную
2. глянуть примеры https://stfalcon.com/ru/blog/post/android-mvvm 
2.1. вынести вью модели в соответствующие фрагменты, убрав лишние зависимости из активити

2021-01-16 14:21 UTC, merged